### ISSUE TITLE
Error message with savefig

### ISSUE THREAD

**Issue by Eetion** [spencerlyon2/PlotlyJS.jl#44]
Thanks for the great package.  Could you explain the following error messages?

	julia> using PlotlyJS

	julia> using Blink

	julia> function linescatter1()
			   trace1 = scatter(;x=1:4, y=[10, 15, 13, 17], mode="markers")
			   trace2 = scatter(;x=2:5, y=[16, 5, 11, 9], mode="lines")
			   trace3 = scatter(;x=1:4, y=[12, 9, 15, 12], mode="lines+markers")
			   plot([trace1, trace2, trace3])
			   return [trace1, trace2, trace3]
		   end
	linescatter1 (generic function with 1 method)

	julia> P = Plot(linescatter1());

	julia> savefig(P,"testsave.html",:local)
	ERROR: PlotlyJS.savefig not available without a frontend. Try calling `PlotlyJS.savefig(SyncPlot(p))` instead
	 in error at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
	 in savefig at /Users/greghenselman/.julia/v0.4/PlotlyJS/src/savefig.jl:196

	julia> PlotlyJS.savefig(SyncPlot(P))
	ERROR: UndefVarError: SyncPlot not defined

Thanks for your help.

**Comment by spencerlyon2** [comment]
The issue here is trying to use the `savefig` family of functions with a `PlotlyJS.Plot` object instead of a `PlotlyJS.SyncPlot` object.

The `plot` function will return a `SyncPlot` where the underlying display type is properly chosen based on your environment (e.g. An electron window if calling `plot` from the REPL and the notebook itself if calling from a Jupiter notebook). This is always the recommended way to create a `SyncPlot`.

The correct way to do this example should be to adjust the `linescatter1` function to return the `SyncPlot` created in the call to `plot` on the second to last line (meaning just delete the last line) and then to do this:

```julia
p = linescatter1()
savefig(p, "testsave.html", :local)
```

That all being said, saving to an html file is actually possible without a frontend, so I should probably implement a method `savefig(::Plot, "___.html")`
