### ISSUE TITLE
Reloaded notebook's PlotlyJS doesn't work

### ISSUE THREAD

**Issue by cstjean** [spencerlyon2/PlotlyJS.jl#45]
Once every five notebooks or so (OSX, Julia 0.4.5, using Plots.jl), the notebook gets in a broken state, such that when I reload it, all PlotlyJS plots have disappeared, and won't come back even after restarting the notebook. The only cure is to 1. Clear all outputs, 2. Save the notebook, 3. Refresh the page. I used to have almost exactly the same problem with Bokeh in python (except that Bokeh was at least printing a red `Javascript error adding output!` message), but it didn't happen as often. My guess is that this isn't Julia specific, but I wanted to get some feedback before posting upstream. Is this a known issue?

**Comment by spencerlyon2** [comment]
Hey @cstjean thanks for posting. This is a known issue. 

I believe the problem is that when you call `using PlotlyJS` in the notebook, it adds the PlotlyJS.jl@noreply.github.com Javascript library as an invisible output of that cell. If that cell gets run a second time then the output is removed, but you as a user have know way of seeing that. Once the output is gone, so is the plotly Javascript and you can no longer create or view figures. 

I belive that one way around this would be to expose a function that can be called at any time to force the Plotly Javascript to be reloaded. I haven't tried this approach yet, but am hopeful that it would work

**Comment by cstjean** [comment]
That's an interesting problem. FWIW, Bokeh notebooks force you to write `Bokeh.output_notebook()` at the top. I assume that's because they haven't found any better solution to the problem in Python. `Plots.jl` already asks users to write `plotlyjs()`. It might be a good place to output the Plotly javascript.

**Comment by malmaud** [comment]
The official Plotly Python package makes you do that to, so it seems eminently reasonable for us to follow suit.

**Comment by spencerlyon2** [comment]
That's too bad. I really liked the magic of `using PlotlyJS` setting up the right frontend depending on context. I guess it isn't a totally feasible solution. 

I'll try to patch that up soon, but if any one beats me to it -- all the better!

**Comment by spencerlyon2** [comment]
Done
