### ISSUE TITLE
Loaded notebooks have no plots

### ISSUE THREAD

**Issue by cstjean** [spencerlyon2/PlotlyJS.jl#89]
On Julia 0.5, in IJulia,

``` julia
# First cell:
using PlotlyJS
init_notebook(true)   # with or without this line, same thing

# Second cell:
t1 = scatter(;x=[1, 2, 3, 4, 5],
              y=[1, 6, 3, 6, 1])
plot([t1])
```

This displays a plot. But if I save the notebook and refresh the page (or reload the notebook later), then all the plots are gone. The above code just displays a blank. Plots.jl displays a "Javascript error" in red. Related to #45.

Bokeh uses [this code](https://github.com/bokeh/bokeh/blob/9650b109b62d385d372eecc1f9d5a511bf4a3d49/bokeh/util/notebook.py#L8). I haven't tried if it would solve the issue.

``` python
    import IPython.core.displaypub as displaypub
    try:
        displaypub.publish_display_data(source, data)
    except TypeError:
        displaypub.publish_display_data(data)
```

**Comment by spencerlyon2** [comment]
Hi @cstjean Thanks for bringing this up.

I'm a little surprised that you're seeing this behavior. One thing that might happen is if you run the `using PlotlyJS` cell more than once, it might remove the (hidden to us) plotly.js javascript source that is loaded when the PlotlyJS first starts up. 

It isn't an issue during the same session, as your browser keeps a local copy of it in memory, but if you leave/refresh/or otherwise re-open the page then it will not be able to resurrect that javascript code.

Can you try to run the `using PlotlyJS` cell only one time, plot something from a different cell, then refresh and see what happens?

If you are still having issues it would be helpful if you could post the offending notebook to github or put it in a github gist so I can investigate more.

**Comment by cstjean** [comment]
Thank you for the detailed answer. You were right; if I follow your steps on a fresh notebook, it works with `using Plotly` upon refresh. `Plots` still fails though. After refreshing the page:

![screen shot 2016-10-21 at 12 23 11](https://cloud.githubusercontent.com/assets/8622776/19610918/fec60d2e-97ac-11e6-9afe-8d37223194d2.png)

Should I close this issue and open it again on Plots.jl? cc. @tbreloff

**Comment by spencerlyon2** [comment]
If it works with PlotlyJS and not Plots it sounds like an issue that should be handled over there.

What do you think @tbreloff ?

**Comment by tbreloff** [comment]
Noted. I'll probably need Spencer's help to solve this even if you open a
new issue in Plots.

**Comment by pabloferz** [comment]
A possible solution could be to have

```julia
function Plots._show(io::IO, ::MIME"image/svg+xml", plt::Plot{Plots.PlotlyJSBackend})
    if Plots.isijulia()
        print(io, PlotlyJS.html_body(plt.o))
    else
        show(io, MIME("text/html"), plt.o)
    end
end
```

in `Plots` instead of the current `_show`definition over there.
